_BASE_: "../../../configs/Base-RetinaNet.yaml"
DATALOADER:
  NUM_WORKERS: 16
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.02
  STEPS: (105000, 125000)
  MAX_ITER: 135000
  WARMUP_FACTOR: 0.0001
  WARMUP_ITERS: 500
