# This configuration is for quantification of training sample size to error relation
_BASE_: "../../../configs/Base-RCNN-FPN.yaml"
MODEL:
  RPN:
    #POST_NMS_TOPK_TEST: 5000
    PRE_NMS_TOPK_TEST: 12000
  DEVICE: "cuda"
  WEIGHTS: "output/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 101

DATALOADER:
  NUM_WORKERS: 4

SOLVER:
  IMS_PER_BATCH: 3
  BASE_LR: 0.0005
  MAX_ITER: 40000
  STEPS: [10000, 20000]
  GAMMA: 0.5

TEST:
  DETECTIONS_PER_IMAGE: 1000
