name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on:
      - macos-latest
      - ubuntu-latest
      - windows-latest
    # if: ${{ github.repository_owner == 'facebookresearch' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11" ]
        torch: [ "1.12", "1.13", "2.0" ]
        include:
          - torch: "1.12"
            torchvision: "0.13.0"
          - torch: "1.13"
            torchvision: "0.14.0"
          - torch: "2.0"
            torchvision: "0.15.0"
        exclude:
          - python: "3.11"
            torch: "1.12"
    env:
      # point datasets to ~/.torch so it's cached by CI
      DETECTRON2_DATASETS: ~/.torch/datasets
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.pythonLocation }}/lib/python${{ matrix.python }}/site-packages
            ~/.torch
          key: ${{ runner.os }}-torch${{ matrix.torch }}-${{ hashFiles('setup.py') }}-20230317
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install ninja opencv-python-headless onnx pytest-xdist
          python -m pip install torch==${{matrix.torch}} torchvision==${{matrix.torchvision}} -f https://download.pytorch.org/whl/torch_stable.html
          # install from github to get latest; install iopath first since fvcore depends on it
          python -m pip install -U 'git+https://github.com/facebookresearch/iopath'
          python -m pip install -U 'git+https://github.com/facebookresearch/fvcore'

      - name: Build and install
        run: |
          CC=clang CXX=clang++ python -m pip install -e .[all]
          python -m detectron2.utils.collect_env
      - name: Create wheel
        run: |
          python -m pip install wheel
          python setup.py bdist_wheel
      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: detectron2-${{ matrix.python }}-${{ matrix.torch }}-wheel
          path: dist/*.whl